spring:
  redis:
    host: 172.16.116.4
    password: complain_workbench|pR&@IO$e
    port: 20000
    timeout: 3000ms

    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 1000ms
        min-idle: 1
    project: BF_WECHAT
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: ${master_url}
      username: ${master_username}
      password: ${master_password}
      filters: stat
      validationQuery: select 'x'
      init-s-q-l: SET NAMES utf8mb4
      initialSize: 5
      maxActive: 50
      maxWait: 60000
      minIdle: 5
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: ${slave_url}
      username: ${slave_username}
      password: ${slave_password}
      filters: stat
      validationQuery: select 'x'
      init-s-q-l: SET NAMES utf8mb4
      initialSize: 5
      maxActive: 50
      maxWait: 60000
      minIdle: 5
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000

logging:
  config: classpath:logback.xml