spring:
  redis:
    host: 172.16.116.49
    password: test|test
    port: 20806
    timeout: 3000ms

    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 1000ms
        min-idle: 1
    project: BF_WECHAT
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost/test?characterEncoding=utf8
      username: root
      password: 123456
      filters: stat
      validationQuery: select 'x'
      init-s-q-l: SET NAMES utf8mb4
      initialSize: 10
      maxActive: 20
      maxWait: 60000
      minIdle: 5
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost/test?characterEncoding=utf8
      username: root
      password: 123456
      filters: stat
      validationQuery: select 'x'
      init-s-q-l: SET NAMES utf8mb4
      initialSize: 10
      maxActive: 20
      maxWait: 60000
      minIdle: 5
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000

mybatis:
  type-aliases-package: win.suroot.dopi.mapper
  mapper-locations: win.suroot.dopi.mapper

logging:
  config: classpath:logback.xml